version: "3.3"

services:
  nginx:
    build:
      context: .
      dockerfile: docker/Nginx.Dockerfile
    ports: 
      - "80:80"
    links:
      - fpm
    volumes:
      - ./:/var/www/html
  fpm:
    build:
      context: .
      dockerfile: docker/Fpm.Dockerfile
    links:
      - mysql
    volumes:
      - ./:/var/www/html
  mysql:
    image: mysql:5.7
    ports:
      - 33061:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=laravel
      
